import "./styles/globals.css";


export const metadata = {
  title: "Next.site",
  description: "Generated by create next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
